apiVersion: v1
kind: Service
metadata:
  name: bdget-service
spec:
  type: NodePort
  selector:
    app: bdget
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
